public class SecurityReport extends Report {

    private VisitorLog visitorLog;
    private int incidentCount;

    public SecurityReport(String generatedBy, VisitorLog visitorLog, int incidentCount) {
        super(generatedBy);
        this.visitorLog = visitorLog;
        this.incidentCount = incidentCount;
    }

    @Override
    public void generateReport() {
        System.out.println("\n========== Security Report [" + reportId + "] ==========");
        System.out.println("Generated By: " + generatedBy + " | On: " + generatedOn);
        System.out.println("Total Visitors  : " + visitorLog.getVisitors().size());
        System.out.println("Total Incidents : " + incidentCount);
        visitorLog.displayAll();
        System.out.println("=====================================================\n");
    }

    @Override
    public String getSummary() {
        return "Security Report [" + reportId + "]: "
                + visitorLog.getVisitors().size() + " visitors, "
                + incidentCount + " incidents.";
    }
}