import java.util.List;

public class FinancialReport extends Report {

    private List<Fee> fees;
    private List<Payment> payments;

    public FinancialReport(String generatedBy, List<Fee> fees, List<Payment> payments) {
        super(generatedBy);
        this.fees = fees;
        this.payments = payments;
    }

    @Override
    public void generateReport() {
        System.out.println("\n========== Financial Report [" + reportId + "] ==========");
        System.out.println("Generated By : " + generatedBy + " | On: " + generatedOn);
        double totalDue = 0, totalPaid = 0;
        for (Fee f : fees) {
            f.display();
            if (f.getStatus() == Fee.Status.PAID) totalPaid += f.getAmount();
            else totalDue += f.getAmount();
        }
        System.out.println("----------------------------------------------------");
        System.out.println("Total Paid    : ₹" + totalPaid);
        System.out.println("Total Pending : ₹" + totalDue);
        System.out.println("====================================================\n");
    }

    @Override
    public String getSummary() {
        return "Financial Report [" + reportId + "]: " + fees.size()
                + " fees, " + payments.size() + " payments.";
    }
}